/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TeButton {
        "host_key": string;
        "url": string;
    }
}
declare global {
    interface HTMLTeButtonElement extends Components.TeButton, HTMLStencilElement {
    }
    var HTMLTeButtonElement: {
        prototype: HTMLTeButtonElement;
        new (): HTMLTeButtonElement;
    };
    interface HTMLElementTagNameMap {
        "te-button": HTMLTeButtonElement;
    }
}
declare namespace LocalJSX {
    interface TeButton {
        "host_key"?: string;
        "url"?: string;
    }
    interface IntrinsicElements {
        "te-button": TeButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "te-button": LocalJSX.TeButton & JSXBase.HTMLAttributes<HTMLTeButtonElement>;
        }
    }
}
